//
// collada1_4Test.cs
//
// This file was generated by XMLSpy 2010r2 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//


using System;
using Altova.Types;

namespace collada1_4
{
	/// <summary>
	/// Summary description for collada1_4Test.
	/// </summary>
	class collada1_4Test
	{
		protected static void Example()
		{
			//
			// TODO:
			//   Insert your code here...
			//
			// Example code to create and save a structure:
			//   collada1_4.collada1_42 doc = collada1_4.collada1_42.CreateDocument();			
			//   collada1_4.visual_sceneType root = doc.visual_scene.Append();
			//   ...
			//   doc.SaveToFile("collada1_41.xml", true);
			//
			// Example code to load and save a structure:
			//   collada1_4.collada1_42 doc = collada1_4.collada1_42.LoadFromFile("collada1_41.xml");
			//   collada1_4.visual_sceneType root = doc.visual_scene.First;
			//   ...
			//   doc.SaveToFile("collada1_41.xml", true);

		}

		/// <summary>
		/// The main entry point for the application.
		/// </summary>
		[STAThread]
		public static int Main(string[] args)
		{
			try
			{
				Console.WriteLine("collada1_4 Test Application");
				Example();
				Console.WriteLine("OK");
				return 0;
			}
			catch (Exception e)
			{
				Console.WriteLine(e);
				return 1;
			}
		}
	}
}
